name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  release-and-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: git config user
        run: |
          git config --global user.name mrm-dev
          git config --global user.email dev@mrmilu.com

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          corepack enable
          pnpm install

      - name: Release
        run: |
          pnpm release
          git push --follow-tags origin master
          pnpm build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: "./package.json"

      - name: Set env for last tag release
        run: echo "LAST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: "C0BJB6V4P"
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":robot_face: New Inversify Generator release :robot_face:\n*<https://github.com/mrmilu/inversify_generator/blob/master/CHANGELOG.md|${{ env.LAST_TAG }}>*"
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
